In [1]:
import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library

In [3]:
!conda install -c anaconda xlrd --yes

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.1.1              |       h7b6447c_0         5.0 MB  anaconda
    xlrd-1.2.0                 |           py36_0         188 KB  anaconda
    certifi-2019.6.16          |           py36_1         156 KB  anaconda
    ------------------------------------------------------------
                                           Total:         5.4 MB

The following packages will be UPDATED:

    certifi: 2019.6.16-py36_1  conda-forge --> 2019.6.16-py36_1 anaconda
    openssl: 1.1.1c-h516909a_0 conda-forge --> 1.1.1-h7b6447c_0 anaconda
    xlrd:    1.1.0-py37_1                  --> 1.2.0-py36_0     anaconda


Downloading and Extracting Packages
openssl-1.1.1        | 5.0 MB    | ##################################### | 100%
xlrd-1.2.0           | 188 KB    | ##################################### | 100%
certifi-2019.6.16    | 156 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

FileNotFoundError: [Errno 2] No such file or directory: 'jupyterlab/labs/DV0101EN/190819-landningsfrekvens-per-flygplats.xlsx'

In [8]:
df_persen = pd.read_excel('190819-landningsfrekvens-per-flygplats.xlsx')
                       

print ('Data read into a pandas dataframe!')

Data read into a pandas dataframe!

In [11]:
df_persen.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 (40),NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Landningsfrekvens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,ARVIDSJAUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Linjefart och ej,NaN,regelbunden trafik,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Övrig trafik,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Utrikes,NaN,Inrikes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Taxiflyg,NaN,Aerial work,Privatflyg,Skolflyg,Militärflyg,Summa total,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,Europa,NaN,Övriga,Summa,NaN,NaN,NaN,NaN,Utrikes,Inrikes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Januari,NaN,43,NaN,0,43,NaN,NaN,NaN,105.0,4,1,0,1,0,5,159,NaN,NaN
14,NaN,Februari,NaN,66,NaN,0,66,NaN,NaN,NaN,95.0,13,3,1,1,1,11,191,NaN,NaN
15,NaN,Mars,NaN,55,NaN,0,55,NaN,NaN,NaN,106.0,10,0,1,32,78,54,336,NaN,NaN
16,NaN,April,NaN,2,NaN,0,2,NaN,NaN,NaN,96.0,0,0,2,7,27,1,135,NaN,NaN
17,NaN,Maj,NaN,0,NaN,0,0,NaN,NaN,NaN,96.0,1,0,0,0,11,0,108,NaN,NaN
18,NaN,Juni,NaN,0,NaN,0,0,NaN,NaN,NaN,84.0,0,0,10,2,26,0,122,NaN,NaN
19,NaN,Juli,NaN,0,NaN,0,0,NaN,NaN,NaN,100.0,0,0,7,3,35,0,145,NaN,NaN